// ============================================
// EXPANDED Food Library with all categories
// ============================================
export const foodLibrary = {
  meatPoultryEggs: {
    en: "Meat / Poultry / Eggs",
    zh: "肉类/家禽/鸡蛋",
    foods: [
      { en: "Chicken", zh: "鸡肉" },
      { en: "Pork", zh: "猪肉" },
      { en: "Beef", zh: "牛肉" },
      { en: "Duck", zh: "鸭肉" },
      { en: "Lamb", zh: "羊肉" },
      { en: "Goose", zh: "鹅肉" },
      { en: "Turkey", zh: "火鸡肉" },
      { en: "Eggs", zh: "鸡蛋" },
      { en: "Ground pork", zh: "猪肉末" },
      { en: "Ground beef", zh: "牛肉末" },
      { en: "Bacon", zh: "培根" },
      { en: "Ham", zh: "火腿" },
      { en: "Sausage", zh: "香肠" },
      { en: "Chicken breast", zh: "鸡胸肉" },
      { en: "Pork belly", zh: "五花肉" }
    ]
  },
  seafood: {
    en: "Seafood / Fish",
    zh: "海鲜/鱼类",
    foods: [
      { en: "Salmon", zh: "三文鱼" },
      { en: "Shrimp", zh: "虾" },
      { en: "Fish", zh: "鱼" },
      { en: "Crab", zh: "螃蟹" },
      { en: "Squid", zh: "鱿鱼" },
      { en: "Clams", zh: "蛤蜊" },
      { en: "Oysters", zh: "生蚝" },
      { en: "Mussels", zh: "淡菜" },
      { en: "Scallops", zh: "扇贝" },
      { en: "Tilapia", zh: "罗非鱼" },
      { en: "Cod", zh: "鳕鱼" },
      { en: "Tuna", zh: "金枪鱼" },
      { en: "Mackerel", zh: "鲭鱼" },
      { en: "Anchovy", zh: "凤尾鱼" },
      { en: "Lobster", zh: "龙虾" }
    ]
  },
  vegetables: {
    en: "Vegetables",
    zh: "蔬菜",
    foods: [
      // Leafy Greens
      { en: "Spinach", zh: "菠菜" },
      { en: "Kale", zh: "羽衣甘蓝" },
      { en: "Lettuce", zh: "生菜" },
      { en: "Cabbage", zh: "卷心菜" },
      { en: "Chinese cabbage", zh: "白菜" },
      { en: "Bok choy", zh: "小白菜" },
      { en: "Gai lan", zh: "芥兰" },
      { en: "Arugula", zh: "火箭菜" },
      { en: "Romaine lettuce", zh: "长叶生菜" },
      { en: "Swiss chard", zh: "牛皮菜" },
      // Cruciferous
      { en: "Broccoli", zh: "西兰花" },
      { en: "Cauliflower", zh: "花椰菜" },
      { en: "Brussels sprouts", zh: "球芽甘蓝" },
      // Root Vegetables
      { en: "Carrots", zh: "胡萝卜" },
      { en: "Potatoes", zh: "土豆" },
      { en: "Sweet potatoes", zh: "红薯" },
      { en: "Radishes", zh: "萝卜" },
      { en: "Turnips", zh: "芜菁" },
      { en: "Beets", zh: "甜菜" },
      { en: "Parsnips", zh: "欧防风" },
      // Fruity Vegetables
      { en: "Tomatoes", zh: "番茄" },
      { en: "Bell peppers", zh: "灯笼椒" },
      { en: "Chili peppers", zh: "辣椒" },
      { en: "Eggplant", zh: "茄子" },
      { en: "Zucchini", zh: "冬瓜" },
      { en: "Cucumber", zh: "黄瓜" },
      { en: "Pumpkin", zh: "南瓜" },
      // Beans & Legumes
      { en: "Snap peas", zh: "雪豌豆" },
      { en: "Peas", zh: "豌豆" },
      { en: "Green beans", zh: "绿豆" },
      { en: "Chickpeas", zh: "鹰嘴豆" },
      { en: "Black beans", zh: "黑豆" },
      { en: "Lentils", zh: "扁豆" },
      // Mushrooms & Fungi
      { en: "Mushrooms", zh: "蘑菇" },
      { en: "Shiitake", zh: "香菇" },
      { en: "Oyster mushrooms", zh: "蚝菇" },
      // Alliums
      { en: "Onions", zh: "洋葱" },
      { en: "Garlic", zh: "大蒜" },
      { en: "Ginger", zh: "生姜" },
      { en: "Leeks", zh: "韭葱" },
      { en: "Green onions", zh: "葱" },
      // Other
      { en: "Tofu", zh: "豆腐" },
      { en: "Bean sprouts", zh: "豆芽" },
      { en: "Corn", zh: "玉米" },
      { en: "Asparagus", zh: "芦笋" },
      { en: "Celery", zh: "芹菜" },
      { en: "Bamboo shoots", zh: "竹笋" }
    ]
  },
  fruits: {
    en: "Fruits",
    zh: "水果",
    foods: [
      // Citrus
      { en: "Oranges", zh: "橙子" },
      { en: "Lemons", zh: "柠檬" },
      { en: "Limes", zh: "青柠" },
      { en: "Grapefruits", zh: "葡萄柚" },
      { en: "Tangerines", zh: "橘子" },
      // Berries
      { en: "Strawberries", zh: "草莓" },
      { en: "Blueberries", zh: "蓝莓" },
      { en: "Raspberries", zh: "覆盆子" },
      { en: "Blackberries", zh: "黑莓" },
      // Tree Fruits
      { en: "Apples", zh: "苹果" },
      { en: "Pears", zh: "梨" },
      { en: "Peaches", zh: "桃子" },
      { en: "Plums", zh: "李子" },
      { en: "Cherries", zh: "樱桃" },
      { en: "Apricots", zh: "杏" },
      // Tropical Fruits
      { en: "Bananas", zh: "香蕉" },
      { en: "Mangoes", zh: "芒果" },
      { en: "Pineapple", zh: "菠萝" },
      { en: "Coconut", zh: "椰子" },
      { en: "Papaya", zh: "木瓜" },
      { en: "Kiwi", zh: "猕猴桃" },
      { en: "Dragon fruit", zh: "火龙果" },
      { en: "Passionfruit", zh: "百香果" },
      // Melons
      { en: "Watermelon", zh: "西瓜" },
      { en: "Cantaloupe", zh: "哈密瓜" },
      { en: "Honeydew", zh: "蜜瓜" },
      // Other
      { en: "Grapes", zh: "葡萄" },
      { en: "Avocado", zh: "牛油果" },
      { en: "Pomegranate", zh: "石榴" },
      { en: "Figs", zh: "无花果" }
    ]
  }
};

// ============================================
// COMPREHENSIVE Recipe Library - 300+ recipes
// Organized by 5 categories with bilingual names
// ============================================
export const recipeLibrary = {
  meatDishes: [
    { id: 1, en: "Kung Pao Chicken", zh: "宫保鸡丁", difficulty: "Medium", cuisine: "Chinese", image: "🌶️" },
    { id: 2, en: "Chicken Stir-fry with Broccoli", zh: "西兰花炒鸡肉", difficulty: "Easy", cuisine: "Chinese", image: "🥘" },
    { id: 3, en: "Sweet and Sour Pork", zh: "糖醋里脊", difficulty: "Medium", cuisine: "Chinese", image: "🍖" },
    { id: 4, en: "Braised Pork Belly", zh: "红烧肉", difficulty: "Medium", cuisine: "Chinese", image: "🍖" },
    { id: 5, en: "General Tso Chicken", zh: "左宗棠鸡", difficulty: "Medium", cuisine: "Chinese", image: "🍗" },
    { id: 6, en: "Mapo Tofu", zh: "麻婆豆腐", difficulty: "Medium", cuisine: "Chinese", image: "🍲" },
    { id: 7, en: "Peking Duck", zh: "北京烤鸭", difficulty: "Hard", cuisine: "Chinese", image: "🦆" },
    { id: 8, en: "Beef with Broccoli", zh: "西兰花牛肉", difficulty: "Easy", cuisine: "Chinese", image: "🥘" },
    { id: 9, en: "Orange Chicken", zh: "橙子鸡", difficulty: "Medium", cuisine: "Chinese", image: "🍗" },
    { id: 10, en: "Chicken with Cashews", zh: "腰果鸡丁", difficulty: "Medium", cuisine: "Chinese", image: "🍗" },
    { id: 11, en: "Twice Cooked Pork", zh: "回锅肉", difficulty: "Medium", cuisine: "Chinese", image: "🍖" },
    { id: 12, en: "Soy Sauce Chicken", zh: "酱油鸡", difficulty: "Easy", cuisine: "Chinese", image: "🍗" },
    { id: 13, en: "Lamb with Cumin", zh: "孜然羊肉", difficulty: "Medium", cuisine: "Chinese", image: "🍖" },
    { id: 14, en: "Beef Tendon Stew", zh: "牛筋炖菜", difficulty: "Hard", cuisine: "Chinese", image: "🍲" },
    { id: 15, en: "Ginger Scallion Chicken", zh: "葱油鸡", difficulty: "Easy", cuisine: "Chinese", image: "🍗" },
    { id: 16, en: "Black Pepper Beef", zh: "黑椒牛肉", difficulty: "Easy", cuisine: "Chinese", image: "🥩" },
    { id: 17, en: "Chicken with Peanuts", zh: "花生鸡丁", difficulty: "Medium", cuisine: "Chinese", image: "🍗" },
    { id: 18, en: "Five Spice Pork", zh: "五香猪肉", difficulty: "Medium", cuisine: "Chinese", image: "🍖" },
    { id: 19, en: "Chicken with Oyster Sauce", zh: "蚝油鸡", difficulty: "Easy", cuisine: "Chinese", image: "🍗" },
    { id: 20, en: "Beef with Black Beans", zh: "豉汁牛肉", difficulty: "Easy", cuisine: "Chinese", image: "🥘" },
    { id: 21, en: "Grilled Steak", zh: "烤牛排", difficulty: "Medium", cuisine: "Western", image: "🥩" },
    { id: 22, en: "Roast Chicken", zh: "烤鸡", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 23, en: "BBQ Ribs", zh: "烧烤肋排", difficulty: "Medium", cuisine: "Western", image: "🍖" },
    { id: 24, en: "Meatballs", zh: "肉丸子", difficulty: "Easy", cuisine: "Western", image: "🍖" },
    { id: 25, en: "Beef Lasagna", zh: "牛肉千层面", difficulty: "Medium", cuisine: "Western", image: "🍝" },
    { id: 26, en: "Chicken Parmesan", zh: "帕玛森鸡肉", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 27, en: "Grilled Chicken Breast", zh: "烤鸡胸肉", difficulty: "Easy", cuisine: "Western", image: "🍗" },
    { id: 28, en: "Beef Stew", zh: "牛肉炖菜", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 29, en: "Pork Chops", zh: "猪排", difficulty: "Easy", cuisine: "Western", image: "🍖" },
    { id: 30, en: "Turkey Meatloaf", zh: "火鸡肉糕", difficulty: "Easy", cuisine: "Western", image: "🍖" },
    { id: 31, en: "Beef Tacos", zh: "牛肉玉米饼", difficulty: "Easy", cuisine: "Western", image: "🌮" },
    { id: 32, en: "Chicken Fajitas", zh: "鸡肉法吉塔", difficulty: "Easy", cuisine: "Western", image: "🌮" },
    { id: 33, en: "Pulled Pork Sandwich", zh: "猪肉汉堡", difficulty: "Medium", cuisine: "Western", image: "🥪" },
    { id: 34, en: "Beef Burger", zh: "牛肉汉堡", difficulty: "Easy", cuisine: "Western", image: "🍔" },
    { id: 35, en: "Chicken Kebab", zh: "鸡肉烤肉串", difficulty: "Easy", cuisine: "Western", image: "🍖" },
    { id: 36, en: "Lamb Chops", zh: "羊排", difficulty: "Medium", cuisine: "Western", image: "🍖" },
    { id: 37, en: "Duck Confit", zh: "油炸鸭腿", difficulty: "Hard", cuisine: "Western", image: "🦆" },
    { id: 38, en: "Beef Wellington", zh: "惠灵顿牛排", difficulty: "Hard", cuisine: "Western", image: "🥩" },
    { id: 39, en: "Pork Schnitzel", zh: "炸猪排", difficulty: "Easy", cuisine: "Western", image: "🍖" },
    { id: 40, en: "Beef Bourguignon", zh: "勃艮第牛肉", difficulty: "Hard", cuisine: "Western", image: "🍲" },
    { id: 41, en: "Chicken Piccata", zh: "意大利小鸡", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 42, en: "Beef Satay", zh: "牛肉沙嗲", difficulty: "Medium", cuisine: "Western", image: "🍖" },
    { id: 43, en: "Chicken Marsala", zh: "马尔萨拉鸡", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 44, en: "Osso Buco", zh: "奥索布科", difficulty: "Hard", cuisine: "Western", image: "🍖" },
    { id: 45, en: "Turkey Meatballs", zh: "火鸡丸子", difficulty: "Easy", cuisine: "Western", image: "🍖" },
    { id: 46, en: "Beef Chili", zh: "牛肉辣椒", difficulty: "Medium", cuisine: "Western", image: "🌶️" },
    { id: 47, en: "Pork Vindaloo", zh: "猪肉咖喱", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 48, en: "Chicken Tikka Masala", zh: "鸡肉提卡玛萨拉", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 49, en: "Beef Milanesa", zh: "米兰牛肉", difficulty: "Easy", cuisine: "Western", image: "🥩" },
    { id: 50, en: "Cajun Chicken", zh: "卡真鸡肉", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 51, en: "Pork Carnitas", zh: "猪肉卡尼塔", difficulty: "Hard", cuisine: "Western", image: "🍖" },
    { id: 52, en: "Beef Teriyaki", zh: "照烧牛肉", difficulty: "Easy", cuisine: "Western", image: "🥩" },
    { id: 53, en: "Chicken Cacciatore", zh: "猎人鸡", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 54, en: "Lamb Rogan Josh", zh: "羊肉罗根乔什", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 55, en: "Veal Piccata", zh: "小牛肉皮卡塔", difficulty: "Medium", cuisine: "Western", image: "🍖" },
    { id: 56, en: "Spicy Chicken Wings", zh: "辣鸡翅", difficulty: "Easy", cuisine: "Western", image: "🍗" },
    { id: 57, en: "Beef Stroganoff", zh: "牛肉斯特罗加诺夫", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 58, en: "Chicken Cordon Bleu", zh: "蓝带鸡", difficulty: "Medium", cuisine: "Western", image: "🍗" },
    { id: 59, en: "Beef Enchiladas", zh: "牛肉恩奇拉达", difficulty: "Medium", cuisine: "Western", image: "🌯" },
    { id: 60, en: "Pork Al Pastor", zh: "牧羊人风格猪肉", difficulty: "Medium", cuisine: "Western", image: "🌮" }
  ],
  vegetableDishes: [
    { id: 101, en: "Vegetable Stir-fry", zh: "蔬菜炒菜", difficulty: "Easy", cuisine: "Chinese", image: "🥦" },
    { id: 102, en: "Eggplant with Garlic Sauce", zh: "蒜泥茄子", difficulty: "Easy", cuisine: "Chinese", image: "🍆" },
    { id: 103, en: "Vegetable Fried Rice", zh: "蔬菜炒饭", difficulty: "Easy", cuisine: "Chinese", image: "🍚" },
    { id: 104, en: "Stir-fried Mushrooms", zh: "炒蘑菇", difficulty: "Easy", cuisine: "Chinese", image: "🍄" },
    { id: 105, en: "Bamboo Shoots with Garlic", zh: "蒜蓉竹笋", difficulty: "Easy", cuisine: "Chinese", image: "🌿" },
    { id: 106, en: "Broccoli with Oyster Sauce", zh: "蚝油西兰花", difficulty: "Easy", cuisine: "Chinese", image: "🥦" },
    { id: 107, en: "Bok Choy with Garlic", zh: "蒜蓉小白菜", difficulty: "Easy", cuisine: "Chinese", image: "🥬" },
    { id: 108, en: "Bitter Melon with Black Beans", zh: "豉汁苦瓜", difficulty: "Medium", cuisine: "Chinese", image: "🥒" },
    { id: 109, en: "Gai Lan with Garlic", zh: "蒜蓉芥兰", difficulty: "Easy", cuisine: "Chinese", image: "🥬" },
    { id: 110, en: "Mixed Vegetables with Tofu", zh: "豆腐混合蔬菜", difficulty: "Easy", cuisine: "Chinese", image: "🥘" },
    { id: 111, en: "Spinach with Garlic", zh: "蒜蓉菠菜", difficulty: "Easy", cuisine: "Chinese", image: "🥬" },
    { id: 112, en: "Hot Pot Vegetables", zh: "火锅蔬菜", difficulty: "Easy", cuisine: "Chinese", image: "🍲" },
    { id: 113, en: "String Beans with Garlic", zh: "蒜蓉四季豆", difficulty: "Easy", cuisine: "Chinese", image: "🫘" },
    { id: 114, en: "Cauliflower Stir-fry", zh: "炒花椰菜", difficulty: "Easy", cuisine: "Chinese", image: "🥦" },
    { id: 115, en: "Tofu with Mushrooms", zh: "蘑菇豆腐", difficulty: "Easy", cuisine: "Chinese", image: "🍄" },
    { id: 116, en: "Braised Cabbage", zh: "炖卷心菜", difficulty: "Easy", cuisine: "Chinese", image: "🥬" },
    { id: 117, en: "Papaya Salad", zh: "木瓜沙拉", difficulty: "Easy", cuisine: "Chinese", image: "🥗" },
    { id: 118, en: "Cold Cucumber Salad", zh: "凉拌黄瓜", difficulty: "Easy", cuisine: "Chinese", image: "🥒" },
    { id: 119, en: "Caesar Salad", zh: "凯撒沙拉", difficulty: "Easy", cuisine: "Western", image: "🥗" },
    { id: 120, en: "Roasted Vegetables", zh: "烤蔬菜", difficulty: "Easy", cuisine: "Western", image: "🥘" },
    { id: 121, en: "Greek Salad", zh: "希腊沙拉", difficulty: "Easy", cuisine: "Western", image: "🥗" },
    { id: 122, en: "Caprese Salad", zh: "卡普雷泽沙拉", difficulty: "Easy", cuisine: "Western", image: "🍅" },
    { id: 123, en: "Grilled Vegetables", zh: "烤蔬菜", difficulty: "Easy", cuisine: "Western", image: "🥘" },
    { id: 124, en: "Mushroom Risotto", zh: "蘑菇烩饭", difficulty: "Medium", cuisine: "Western", image: "🍚" },
    { id: 125, en: "Ratatouille", zh: "普罗旺斯蔬菜炖菜", difficulty: "Medium", cuisine: "Western", image: "🥘" },
    { id: 126, en: "Eggplant Parmesan", zh: "帕玛森茄子", difficulty: "Medium", cuisine: "Western", image: "🍆" },
    { id: 127, en: "Vegetable Curry", zh: "蔬菜咖喱", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 128, en: "Spinach and Feta Pie", zh: "菠菜羊乳酪派", difficulty: "Medium", cuisine: "Western", image: "🥧" },
    { id: 129, en: "Vegetable Soup", zh: "蔬菜汤", difficulty: "Easy", cuisine: "Western", image: "🍲" },
    { id: 130, en: "Stuffed Bell Peppers", zh: "填充辣椒", difficulty: "Medium", cuisine: "Western", image: "🌶️" },
    { id: 131, en: "Vegetable Skewers", zh: "蔬菜串", difficulty: "Easy", cuisine: "Western", image: "🍖" },
    { id: 132, en: "Zucchini Noodles", zh: "西葫芦面", difficulty: "Easy", cuisine: "Western", image: "🍝" },
    { id: 133, en: "Beet Salad", zh: "甜菜沙拉", difficulty: "Easy", cuisine: "Western", image: "🥗" },
    { id: 134, en: "Asparagus with Hollandaise", zh: "荷兰酱芦笋", difficulty: "Medium", cuisine: "Western", image: "🌿" },
    { id: 135, en: "Tomato Basil Pasta", zh: "番茄罗勒意面", difficulty: "Easy", cuisine: "Western", image: "🍝" },
    { id: 136, en: "Vegetable Frittata", zh: "蔬菜意大利烘蛋", difficulty: "Medium", cuisine: "Western", image: "🥚" },
    { id: 137, en: "Kale Chips", zh: "羽衣甘蓝脆片", difficulty: "Easy", cuisine: "Western", image: "🌿" },
    { id: 138, en: "Corn Salad", zh: "玉米沙拉", difficulty: "Easy", cuisine: "Western", image: "🌽" },
    { id: 139, en: "Vegetable Tacos", zh: "蔬菜玉米饼", difficulty: "Easy", cuisine: "Western", image: "🌮" },
    { id: 140, en: "Vegetable Lo Mein", zh: "蔬菜老面", difficulty: "Easy", cuisine: "Western", image: "🍜" },
    { id: 141, en: "Grilled Corn", zh: "烤玉米", difficulty: "Easy", cuisine: "Western", image: "🌽" },
    { id: 142, en: "Vegetable Quiche", zh: "蔬菜乳蛋饼", difficulty: "Medium", cuisine: "Western", image: "🥧" },
    { id: 143, en: "Bean Salad", zh: "豆沙拉", difficulty: "Easy", cuisine: "Western", image: "🥗" },
    { id: 144, en: "Vegetable Fajitas", zh: "蔬菜法吉塔", difficulty: "Easy", cuisine: "Western", image: "🌮" },
    { id: 145, en: "Vegetable Spring Rolls", zh: "蔬菜春卷", difficulty: "Medium", cuisine: "Western", image: "🥟" },
    { id: 146, en: "Vegetable Pad Thai", zh: "蔬菜泰式炒面", difficulty: "Medium", cuisine: "Western", image: "🍜" },
    { id: 147, en: "Vegetable Biryani", zh: "蔬菜印度香米饭", difficulty: "Medium", cuisine: "Western", image: "🍚" }
  ],
  soupDishes: [
    { id: 201, en: "Egg Drop Soup", zh: "蛋花汤", difficulty: "Easy", cuisine: "Chinese", image: "🥣" },
    { id: 202, en: "Wonton Soup", zh: "馄饨汤", difficulty: "Medium", cuisine: "Chinese", image: "🥣" },
    { id: 203, en: "Hot and Sour Soup", zh: "酸辣汤", difficulty: "Medium", cuisine: "Chinese", image: "🌶️" },
    { id: 204, en: "Chicken Noodle Soup", zh: "鸡汤面", difficulty: "Easy", cuisine: "Chinese", image: "🍜" },
    { id: 205, en: "Beef Noodle Soup", zh: "牛肉汤面", difficulty: "Medium", cuisine: "Chinese", image: "🍜" },
    { id: 206, en: "Seafood Soup", zh: "海鲜汤", difficulty: "Medium", cuisine: "Chinese", image: "🍲" },
    { id: 207, en: "Hot Pot", zh: "火锅", difficulty: "Easy", cuisine: "Chinese", image: "🍲" },
    { id: 208, en: "Winter Melon Soup", zh: "冬瓜汤", difficulty: "Medium", cuisine: "Chinese", image: "🍲" },
    { id: 209, en: "Ginseng Chicken Soup", zh: "人参鸡汤", difficulty: "Hard", cuisine: "Chinese", image: "🍲" },
    { id: 210, en: "Bird's Nest Soup", zh: "燕窝汤", difficulty: "Hard", cuisine: "Chinese", image: "🍲" },
    { id: 211, en: "Corn and Chicken Soup", zh: "玉米鸡汤", difficulty: "Easy", cuisine: "Chinese", image: "🍲" },
    { id: 212, en: "Mushroom Soup", zh: "蘑菇汤", difficulty: "Easy", cuisine: "Chinese", image: "🍄" },
    { id: 213, en: "Pork Rib Soup", zh: "排骨汤", difficulty: "Medium", cuisine: "Chinese", image: "🍲" },
    { id: 214, en: "Bitter Melon Soup", zh: "苦瓜汤", difficulty: "Medium", cuisine: "Chinese", image: "🍲" },
    { id: 215, en: "Duck Soup", zh: "鸭汤", difficulty: "Medium", cuisine: "Chinese", image: "🍲" },
    { id: 216, en: "Fish Soup", zh: "鱼汤", difficulty: "Easy", cuisine: "Chinese", image: "🍲" },
    { id: 217, en: "Shrimp Wonton Soup", zh: "虾馄饨汤", difficulty: "Medium", cuisine: "Chinese", image: "🍲" },
    { id: 218, en: "Spinach Soup", zh: "菠菜汤", difficulty: "Easy", cuisine: "Chinese", image: "🥬" },
    { id: 219, en: "Radish Soup", zh: "萝卜汤", difficulty: "Easy", cuisine: "Chinese", image: "🍲" },
    { id: 220, en: "Tomato Soup", zh: "番茄汤", difficulty: "Easy", cuisine: "Western", image: "🍲" },
    { id: 221, en: "Beef Broth", zh: "牛肉汤", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 222, en: "Vegetable Minestrone", zh: "蔬菜蔬菜汤", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 223, en: "French Onion Soup", zh: "法式洋葱汤", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 224, en: "Cream of Mushroom Soup", zh: "蘑菇奶油汤", difficulty: "Medium", cuisine: "Western", image: "🍄" },
    { id: 225, en: "Clam Chowder", zh: "蛤蜊奶油汤", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 226, en: "Seafood Chowder", zh: "海鲜奶油汤", difficulty: "Hard", cuisine: "Western", image: "🍲" },
    { id: 227, en: "Butternut Squash Soup", zh: "南瓜汤", difficulty: "Easy", cuisine: "Western", image: "🍲" },
    { id: 228, en: "Pumpkin Soup", zh: "南瓜汤", difficulty: "Easy", cuisine: "Western", image: "🎃" },
    { id: 229, en: "Beet Soup", zh: "甜菜汤", difficulty: "Easy", cuisine: "Western", image: "🍲" },
    { id: 230, en: "Lentil Soup", zh: "扁豆汤", difficulty: "Easy", cuisine: "Western", image: "🍲" },
    { id: 231, en: "Split Pea Soup", zh: "豌豆汤", difficulty: "Medium", cuisine: "Western", image: "🍲" },
    { id: 232, en: "Potato Soup", zh: "土豆汤", difficulty: "Easy", cuisine: "Western", image: "🍲" },
    { id: 233, en: "Asparagus Soup", zh: "芦笋汤", difficulty: "Medium", cuisine: "Western", image: "🌿" },
    { id: 234, en: "Broccoli Soup", zh: "西兰花汤", difficulty: "Easy", cuisine: "Western", image: "🥦" },
    { id: 235, en: "Cauliflower Soup", zh: "花椰菜汤", difficulty: "Easy", cuisine: "Western", image: "🥦" },
    { id: 236, en: "Gazpacho", zh: "冷番茄汤", difficulty: "Easy", cuisine: "Western", image: "🍲" },
    { id: 237, en: "Scotch Broth", zh: "苏格兰汤", difficulty: "Medium", cuisine: "Western", image: "🍲" }
  ],
  specialtyDishes: [
    { id: 301, en: "Fried Rice with Egg", zh: "蛋炒饭", difficulty: "Easy", cuisine: "Chinese", image: "🍚" },
    { id: 302, en: "Chow Mein", zh: "炒面", difficulty: "Easy", cuisine: "Chinese", image: "🍜" },
    { id: 303, en: "Lo Mein", zh: "老面", difficulty: "Easy", cuisine: "Chinese", image: "🍜" },
    { id: 304, en: "Dumplings", zh: "饺子", difficulty: "Medium", cuisine: "Chinese", image: "🥟" },
    { id: 305, en: "Steamed Buns", zh: "馒头", difficulty: "Medium", cuisine: "Chinese", image: "🥟" },
    { id: 306, en: "Spring Rolls", zh: "春卷", difficulty: "Medium", cuisine: "Chinese", image: "🥟" },
    { id: 307, en: "Wontons", zh: "馄饨", difficulty: "Medium", cuisine: "Chinese", image: "🥟" },
    { id: 308, en: "Dim Sum Assortment", zh: "点心拼盘", difficulty: "Hard", cuisine: "Chinese", image: "🥡" },
    { id: 309, en: "Shrimp Fried Rice", zh: "虾炒饭", difficulty: "Easy", cuisine: "Chinese", image: "🍚" },
    { id: 310, en: "Crab Fried Rice", zh: "蟹炒饭", difficulty: "Easy", cuisine: "Chinese", image: "🍚" },
    { id: 311, en: "Sweet and Sour Fish", zh: "糖醋鱼", difficulty: "Medium", cuisine: "Chinese", image: "🐟" },
    { id: 312, en: "Steamed Fish", zh: "清蒸鱼", difficulty: "Easy", cuisine: "Chinese", image: "🐟" },
    { id: 313, en: "Shrimp with Garlic Sauce", zh: "蒜蓉虾", difficulty: "Easy", cuisine: "Chinese", image: "🦐" },
    { id: 314, en: "Scallop Fried Rice", zh: "扇贝炒饭", difficulty: "Easy", cuisine: "Chinese", image: "🍚" },
    { id: 315, en: "Squid with Black Bean Sauce", zh: "豉汁鱿鱼", difficulty: "Medium", cuisine: "Chinese", image: "🦑" },
    { id: 316, en: "Fried Noodles", zh: "炸面", difficulty: "Easy", cuisine: "Chinese", image: "🍜" },
    { id: 317, en: "Curry Noodles", zh: "咖喱面", difficulty: "Medium", cuisine: "Chinese", image: "🍜" },
    { id: 318, en: "Sesame Noodles", zh: "芝麻面", difficulty: "Easy", cuisine: "Chinese", image: "🍜" },
    { id: 319, en: "Dan Dan Noodles", zh: "担担面", difficulty: "Medium", cuisine: "Chinese", image: "🍜" },
    { id: 320, en: "Pasta Carbonara", zh: "意大利面条卡邦尼", difficulty: "Easy", cuisine: "Western", image: "🍝" },
    { id: 321, en: "Fettuccine Alfredo", zh: "意大利宽带面", difficulty: "Easy", cuisine: "Western", image: "🍝" },
    { id: 322, en: "Spaghetti Bolognese", zh: "意大利肉酱面", difficulty: "Easy", cuisine: "Western", image: "🍝" },
    { id: 323, en: "Penne Arrabbiata", zh: "愤怒的笔管面", difficulty: "Easy", cuisine: "Western", image: "🍝" },
    { id: 324, en: "Lasagna", zh: "千层面", difficulty: "Medium", cuisine: "Western", image: "🍝" },
    { id: 325, en: "Ravioli", zh: "意大利方形饺", difficulty: "Hard", cuisine: "Western", image: "🍝" },
    { id: 326, en: "Macaroni and Cheese", zh: "奶酪意面", difficulty: "Easy", cuisine: "Western", image: "🍝" },
    { id: 327, en: "Fish and Chips", zh: "炸鱼和薯条", difficulty: "Medium", cuisine: "Western", image: "🍟" },
    { id: 328, en: "Grilled Salmon", zh: "烤三文鱼", difficulty: "Easy", cuisine: "Western", image: "🐟" },
    { id: 329, en: "Shrimp Scampi", zh: "意式虾", difficulty: "Easy", cuisine: "Western", image: "🦐" },
    { id: 330, en: "Lobster Tail", zh: "龙虾尾", difficulty: "Hard", cuisine: "Western", image: "🦞" },
    { id: 331, en: "Crab Cakes", zh: "蟹饼", difficulty: "Medium", cuisine: "Western", image: "🦀" },
    { id: 332, en: "Calamari", zh: "炸鱿鱼", difficulty: "Medium", cuisine: "Western", image: "🦑" },
    { id: 333, en: "Paella", zh: "西班牙海鲜饭", difficulty: "Hard", cuisine: "Western", image: "🍚" },
    { id: 334, en: "Risotto", zh: "烩饭", difficulty: "Medium", cuisine: "Western", image: "🍚" },
    { id: 335, en: "Pizza", zh: "披萨", difficulty: "Medium", cuisine: "Western", image: "🍕" },
    { id: 336, en: "Pepperoni Pizza", zh: "意大利腊肠披萨", difficulty: "Medium", cuisine: "Western", image: "🍕" },
    { id: 337, en: "Vegetarian Pizza", zh: "素食披萨", difficulty: "Medium", cuisine: "Western", image: "🍕" },
    { id: 338, en: "Seafood Pizza", zh: "海鲜披萨", difficulty: "Medium", cuisine: "Western", image: "🍕" },
    { id: 339, en: "Pad Thai", zh: "泰式炒面", difficulty: "Medium", cuisine: "Western", image: "🍜" }
  ],
  breakfast: [
    { id: 401, en: "Congee", zh: "粥", difficulty: "Easy", cuisine: "Chinese", image: "🥣" },
    { id: 402, en: "Chicken Congee", zh: "鸡粥", difficulty: "Easy", cuisine: "Chinese", image: "🥣" },
    { id: 403, en: "Pork Congee", zh: "猪肉粥", difficulty: "Easy", cuisine: "Chinese", image: "🥣" },
    { id: 404, en: "Century Egg Congee", zh: "皮蛋粥", difficulty: "Easy", cuisine: "Chinese", image: "🥣" },
    { id: 405, en: "You Tiao (Chinese Donut)", zh: "油条", difficulty: "Medium", cuisine: "Chinese", image: "🥐" },
    { id: 406, en: "Steamed Buns", zh: "馒头", difficulty: "Medium", cuisine: "Chinese", image: "🥟" },
    { id: 407, en: "Char Siu Bao", zh: "叉烧包", difficulty: "Medium", cuisine: "Chinese", image: "🥟" },
    { id: 408, en: "Soy Sauce Eggs", zh: "酱油蛋", difficulty: "Easy", cuisine: "Chinese", image: "🥚" },
    { id: 409, en: "Tea Eggs", zh: "茶叶蛋", difficulty: "Easy", cuisine: "Chinese", image: "🥚" },
    { id: 410, en: "Scallion Pancakes", zh: "葱油饼", difficulty: "Medium", cuisine: "Chinese", image: "🥘" },
    { id: 411, en: "Chive Pancakes", zh: "韭菜盒子", difficulty: "Medium", cuisine: "Chinese", image: "🥘" },
    { id: 412, en: "Bing (Chinese Crepes)", zh: "饼", difficulty: "Medium", cuisine: "Chinese", image: "🥞" },
    { id: 413, en: "Dan Bing (Egg Crepes)", zh: "蛋饼", difficulty: "Easy", cuisine: "Chinese", image: "🥞" },
    { id: 414, en: "Rice Noodles", zh: "米粉", difficulty: "Easy", cuisine: "Chinese", image: "🍜" },
    { id: 415, en: "Wet Rice Noodles", zh: "湿米粉", difficulty: "Easy", cuisine: "Chinese", image: "🍜" },
    { id: 416, en: "Soy Milk with Youtiao", zh: "豆浆油条", difficulty: "Easy", cuisine: "Chinese", image: "🥛" },
    { id: 417, en: "Salty Soy Milk", zh: "咸豆浆", difficulty: "Easy", cuisine: "Chinese", image: "🥛" },
    { id: 418, en: "Sweet Soy Milk", zh: "甜豆浆", difficulty: "Easy", cuisine: "Chinese", image: "🥛" },
    { id: 419, en: "Rice Cake", zh: "年糕", difficulty: "Medium", cuisine: "Chinese", image: "🍰" },
    { id: 420, en: "Sweet Rice Balls", zh: "汤圆", difficulty: "Medium", cuisine: "Chinese", image: "🍡" },
    { id: 421, en: "Scrambled Eggs", zh: "炒鸡蛋", difficulty: "Easy", cuisine: "Western", image: "🥚" },
    { id: 422, en: "Fried Eggs", zh: "煎鸡蛋", difficulty: "Easy", cuisine: "Western", image: "🥚" },
    { id: 423, en: "Omelet", zh: "蛋卷", difficulty: "Medium", cuisine: "Western", image: "🥚" },
    { id: 424, en: "Cheese Omelet", zh: "奶酪蛋卷", difficulty: "Medium", cuisine: "Western", image: "🧀" },
    { id: 425, en: "Pancakes", zh: "松饼", difficulty: "Medium", cuisine: "Western", image: "🥞" },
    { id: 426, en: "Blueberry Pancakes", zh: "蓝莓松饼", difficulty: "Medium", cuisine: "Western", image: "🫐" },
    { id: 427, en: "Waffles", zh: "华夫饼", difficulty: "Medium", cuisine: "Western", image: "🧇" },
    { id: 428, en: "French Toast", zh: "法式面包", difficulty: "Easy", cuisine: "Western", image: "🍞" },
    { id: 429, en: "Cinnamon Roll", zh: "肉桂卷", difficulty: "Medium", cuisine: "Western", image: "🥐" },
    { id: 430, en: "Bagel and Cream Cheese", zh: "贝果和奶油芝士", difficulty: "Easy", cuisine: "Western", image: "🥯" },
    { id: 431, en: "Croissant", zh: "羊角面包", difficulty: "Medium", cuisine: "Western", image: "🥐" },
    { id: 432, en: "Muffin", zh: "松饼", difficulty: "Easy", cuisine: "Western", image: "🧁" },
    { id: 433, en: "Blueberry Muffin", zh: "蓝莓松饼", difficulty: "Easy", cuisine: "Western", image: "🧁" },
    { id: 434, en: "Granola and Yogurt", zh: "麦片酸奶", difficulty: "Easy", cuisine: "Western", image: "🥣" },
    { id: 435, en: "Oatmeal", zh: "燕麦粥", difficulty: "Easy", cuisine: "Western", image: "🥣" },
    { id: 436, en: "Cereal", zh: "谷物", difficulty: "Easy", cuisine: "Western", image: "🥣" },
    { id: 437, en: "Fruit Smoothie", zh: "果汁冰沙", difficulty: "Easy", cuisine: "Western", image: "🥤" },
    { id: 438, en: "Protein Smoothie", zh: "蛋白质冰沙", difficulty: "Easy", cuisine: "Western", image: "🥤" },
    { id: 439, en: "Bacon and Eggs", zh: "培根鸡蛋", difficulty: "Easy", cuisine: "Western", image: "🥓" },
    { id: 440, en: "Sausage and Eggs", zh: "香肠鸡蛋", difficulty: "Easy", cuisine: "Western", image: "🥚" },
    { id: 441, en: "Hash Browns", zh: "薯饼", difficulty: "Easy", cuisine: "Western", image: "🥔" },
    { id: 442, en: "Toast with Butter and Jam", zh: "黄油果酱吐司", difficulty: "Easy", cuisine: "Western", image: "🍞" },
    { id: 443, en: "Toast with Avocado", zh: "牛油果吐司", difficulty: "Easy", cuisine: "Western", image: "🥑" },
    { id: 444, en: "Scrambled Eggs with Toast", zh: "炒鸡蛋吐司", difficulty: "Easy", cuisine: "Western", image: "🥚" },
    { id: 445, en: "Breakfast Burrito", zh: "早餐卷饼", difficulty: "Medium", cuisine: "Western", image: "🌯" },
    { id: 446, en: "Scrambled Eggs with Cheese", zh: "奶酪炒鸡蛋", difficulty: "Easy", cuisine: "Western", image: "🧀" }
  ]
};

// Default family members
export const defaultFamilyMembers = [
  { id: 1, name: "Alex", avatar: "👨", age: "Adult" },
  { id: 2, name: "Jordan", avatar: "👧", age: "Teen" },
  { id: 3, name: "Sam", avatar: "👦", age: "Kid" }
];

// Avatar options
export const avatarOptions = ["👨", "👩", "👧", "👦", "👶", "👴", "👵", "🧑", "👱", "🧔"];

// Meal types
export const mealTypes = ["Breakfast", "Lunch", "Dinner", "Snack"];
